export type IUnit = unitEnum | null;

export enum unitEnum {
  MILLIGRAM = "mg",
  GRAM = "g",
  KILOGRAM = "kg",
  LITER = "l",
  MILLILITER = "ml",
  PIECE = "pièce",
  TABLESPOON = "cuillère à soupe",
  TEASPOON = "cuillère à café",
  PINCH = "pincée",
  CUP = "tasse",
  SLICE = "tranche",
  CLOVE = "gousse",
  SPRIG = "brin",
  BUNCH = "bouquet",
}

export const unitMapping: Record<string, unitEnum> = {
  // mg
  mg: unitEnum.MILLIGRAM,
  milligramme: unitEnum.MILLIGRAM,
  milligrammes: unitEnum.MILLIGRAM,
  milligram: unitEnum.MILLIGRAM,
  milligrams: unitEnum.MILLIGRAM,
  "milligramme(s)": unitEnum.MILLIGRAM,
  "milligram(s)": unitEnum.MILLIGRAM,
  // g
  g: unitEnum.GRAM,
  gramme: unitEnum.GRAM,
  grammes: unitEnum.GRAM,
  gram: unitEnum.GRAM,
  grams: unitEnum.GRAM,
  "gramme(s)": unitEnum.GRAM,
  "gram(s)": unitEnum.GRAM,
  // kg
  kg: unitEnum.KILOGRAM,
  kilogramme: unitEnum.KILOGRAM,
  kilogrammes: unitEnum.KILOGRAM,
  kilogram: unitEnum.KILOGRAM,
  kilograms: unitEnum.KILOGRAM,
  kilo: unitEnum.KILOGRAM,
  kilos: unitEnum.KILOGRAM,
  "kilo(s)": unitEnum.KILOGRAM,
  "kilogramme(s)": unitEnum.KILOGRAM,
  "kilogram(s)": unitEnum.KILOGRAM,
  "kilo gramme": unitEnum.KILOGRAM,
  "kilo grammes": unitEnum.KILOGRAM,
  "kilo grammes(s)": unitEnum.KILOGRAM,
  // l
  l: unitEnum.LITER,
  litre: unitEnum.LITER,
  litres: unitEnum.LITER,
  liter: unitEnum.LITER,
  liters: unitEnum.LITER,
  "litre(s)": unitEnum.LITER,
  "liter(s)": unitEnum.LITER,
  // ml
  ml: unitEnum.MILLILITER,
  millilitre: unitEnum.MILLILITER,
  millilitres: unitEnum.MILLILITER,
  milliliter: unitEnum.MILLILITER,
  milliliters: unitEnum.MILLILITER,
  "millilitre(s)": unitEnum.MILLILITER,
  "milliliter(s)": unitEnum.MILLILITER,
  // pièce
  pièce: unitEnum.PIECE,
  pièces: unitEnum.PIECE,
  "pièce(s)": unitEnum.PIECE,
  // c. à soupe
  "c. à soupe": unitEnum.TABLESPOON,
  "c. à soupes": unitEnum.TABLESPOON,
  "c. à soupe(s)": unitEnum.TABLESPOON,
  "cuillère à soupe": unitEnum.TABLESPOON,
  "cuillères à soupe": unitEnum.TABLESPOON,
  "cuillère à soupe(s)": unitEnum.TABLESPOON,
  càs: unitEnum.TABLESPOON,
  tablespoon: unitEnum.TABLESPOON,
  tablespoons: unitEnum.TABLESPOON,
  "tablespoon(s)": unitEnum.TABLESPOON,
  // c. à café
  "c. à café": unitEnum.TEASPOON,
  "c. à cafés": unitEnum.TEASPOON,
  "cuillère à café": unitEnum.TEASPOON,
  "cuillères à café": unitEnum.TEASPOON,
  "cuillère à café(s)": unitEnum.TEASPOON,
  càc: unitEnum.TEASPOON,
  teaspoon: unitEnum.TEASPOON,
  teaspoons: unitEnum.TEASPOON,
  "teaspoon(s)": unitEnum.TEASPOON,
  // pincée
  pincée: unitEnum.PINCH,
  pincées: unitEnum.PINCH,
  "pincée(s)": unitEnum.PINCH,
  pinch: unitEnum.PINCH,
  pinches: unitEnum.PINCH,
  "pinch(s)": unitEnum.PINCH,
  // brin
  brin: unitEnum.SPRIG,
  brins: unitEnum.SPRIG,
  "brin(s)": unitEnum.SPRIG,
  sprig: unitEnum.SPRIG,
  sprigs: unitEnum.SPRIG,
  "sprig(s)": unitEnum.SPRIG,
  // bouquet
  bouquet: unitEnum.BUNCH,
  bouquets: unitEnum.BUNCH,
  "bouquet(s)": unitEnum.BUNCH,
  bunch: unitEnum.BUNCH,
  bunches: unitEnum.BUNCH,
  "bunch(s)": unitEnum.BUNCH,
  // tasse
  tasse: unitEnum.CUP,
  tasses: unitEnum.CUP,
  "tasse(s)": unitEnum.CUP,
  cup: unitEnum.CUP,
  cups: unitEnum.CUP,
  "cup(s)": unitEnum.CUP,
  // tranche
  tranche: unitEnum.SLICE,
  tranches: unitEnum.SLICE,
  "tranche(s)": unitEnum.SLICE,
  slice: unitEnum.SLICE,
  slices: unitEnum.SLICE,
  "slice(s)": unitEnum.SLICE,
  // gousse
  gousse: unitEnum.CLOVE,
  gousses: unitEnum.CLOVE,
  "gousse(s)": unitEnum.CLOVE,
  clove: unitEnum.CLOVE,
  cloves: unitEnum.CLOVE,
  "clove(s)": unitEnum.CLOVE,
};
